#!/bin/bash
ip link set dev eth0 up
ip link set dev eth1 up
ip address add 170.4.255.17/28 dev eth1
ip address add 192.168.150.129/25 dev eth0
echo 1 > /proc/sys/net/ipv4/ip_forward
ip route add default via 170.4.255.18
service isc-dhcp-server start
dhclient eth0
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
