#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/BOX ./files/BOX/etc/scripts/init
  cp ./scripts/FAI_acces ./files/FAI_acces/etc/scripts/init
  cp ./scripts/FAI_interconnexion ./files/FAI_interconnexion/etc/scripts/init
  cp ./scripts/FAI_services ./files/FAI_services/etc/scripts/init
  cp ./scripts/S_WEB ./files/S_WEB/var/scripts/init
  cp ./scripts/S_FTP ./files/S_FTP/etc/scripts/init
  cp ./scripts/S_DNS ./files/S_DNS/etc/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
